version: '3'

services:
  ollama-proxy:
    image: nginx:alpine
    ports:
      - "12434:80"  # Changed from 8080 to 12434 to avoid conflicts
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows accessing host services 